# Generated by Django 3.2.3 on 2021-05-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='Название книги')),
                ('book_photo', models.ImageField(upload_to='', verbose_name='book img')),
                ('book_price', models.FloatField(verbose_name='price')),
                ('created', models.DateTimeField(verbose_name='Дата внесения в БД')),
                ('published', models.IntegerField(blank=True, verbose_name='Год издания')),
                ('pages', models.IntegerField(blank=True, verbose_name='Страниц')),
                ('pereplet', models.BooleanField(blank=True, verbose_name='Твердый переплет')),
                ('ISBN', models.CharField(default=None, max_length=100, verbose_name='ISBN')),
                ('weight', models.IntegerField(default=None, verbose_name='Вес')),
                ('age_protect', models.CharField(default=None, max_length=30, verbose_name='Возратсные ограничения')),
                ('active', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Дата правки')),
            ],
        ),
        migrations.CreateModel(
            name='Spr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Авторство')),
                ('series', models.CharField(max_length=100, verbose_name='Серия')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('publisher', models.CharField(max_length=100, verbose_name='Издательствто')),
            ],
        ),
    ]
