# Generated by Django 3.2.3 on 2021-09-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=35, verbose_name='Автор')),
            ],
            options={
                'verbose_name': ('Автор',),
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': ('Жанр',),
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=35, verbose_name='Издательство')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=35, verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серия',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='default', max_length=100, verbose_name='Название книги')),
                ('book_photo', models.ImageField(blank=True, upload_to='books/', verbose_name='book img')),
                ('book_price', models.FloatField(default=100, verbose_name='price')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в БД')),
                ('published', models.IntegerField(blank=True, verbose_name='Год издания')),
                ('pages', models.IntegerField(blank=True, verbose_name='Страниц')),
                ('pereplet', models.BooleanField(blank=True, verbose_name='Твердый переплет')),
                ('ISBN', models.CharField(default=None, max_length=100, verbose_name='ISBN')),
                ('weight', models.IntegerField(default=None, verbose_name='Вес')),
                ('age_protect', models.CharField(default=None, max_length=30, verbose_name='Возратсные ограничения')),
                ('active', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Дата правки')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('author', models.ManyToManyField(default=1, to='books.Author')),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.genre')),
                ('publisher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='books.publisher')),
                ('series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='books.series')),
            ],
            options={
                'verbose_name': ('Книга',),
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
