# Generated by Django 3.2.3 on 2021-09-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(default=[0], to='books.Author'),
        ),
    ]
