# Generated by Django 3.2.3 on 2021-05-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': ('Книга',), 'verbose_name_plural': 'Книги'},
        ),
    ]
