# Generated by Django 3.2.3 on 2021-09-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.CharField(max_length=35, unique=True, verbose_name='Автор'),
        ),
    ]
