# Generated by Django 3.2.3 on 2021-05-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=35, verbose_name='Автор')),
            ],
            options={
                'verbose_name': ('Автор',),
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.DeleteModel(
            name='Spr',
        ),
    ]
