# Generated by Django 3.2.3 on 2021-05-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210522_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серия'},
        ),
    ]
