# Generated by Django 3.2.3 on 2021-05-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_series_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Издательство', 'verbose_name_plural': 'Издательства'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серия', 'verbose_name_plural': 'Серия'},
        ),
    ]
