# Generated by Django 3.2.3 on 2021-05-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210522_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_price',
            field=models.FloatField(default=100, verbose_name='price'),
        ),
    ]
