# Generated by Django 3.2.3 on 2021-06-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20210529_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_photo',
            field=models.ImageField(upload_to='books/', verbose_name='book img'),
        ),
    ]
