# Generated by Django 3.2.3 on 2021-07-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
