# Generated by Django 3.2.3 on 2021-09-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_photo',
            field=models.ImageField(blank=True, upload_to='books/', verbose_name='book img'),
        ),
    ]
