# Generated by Django 3.2.3 on 2021-06-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_booksincart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_books', models.IntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('books', models.ManyToManyField(related_name='book_carts', to='carts.BooksInCart')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart', verbose_name='Cart')),
            ],
        ),
    ]
