# Generated by Django 3.2.3 on 2021-06-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Логин')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('fname', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('lname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('extra', models.TextField(blank=True, verbose_name='Дополнительная информация')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('index', models.IntegerField(verbose_name='Индекс')),
                ('adress1', models.CharField(max_length=170, verbose_name='Адрес 1')),
                ('adress2', models.CharField(max_length=170, verbose_name='Адрес 2')),
            ],
        ),
    ]
