# Generated by Django 3.2.3 on 2021-06-19 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210615_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': ('Пользователь',), 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adress1',
            field=models.CharField(blank=True, max_length=170, null=True, verbose_name='Адрес 1'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adress2',
            field=models.CharField(blank=True, max_length=170, null=True, verbose_name='Адрес 2'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='extra',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='Индекс')),
                ('adress1', models.CharField(blank=True, max_length=170, null=True, verbose_name='Адрес 1')),
                ('adress2', models.CharField(blank=True, max_length=170, null=True, verbose_name='Адрес 2')),
                ('extra', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
