# Generated by Django 3.2.3 on 2021-09-03 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Новый', max_length=35, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.TextField(verbose_name='Contact info')),
                ('phone', models.TextField(verbose_name='Телефон')),
                ('country', models.TextField(verbose_name='Страна')),
                ('city', models.TextField(verbose_name='Город')),
                ('index', models.TextField(verbose_name='Индекс')),
                ('adress', models.TextField(verbose_name='Адрес')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('books', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_books', to='carts.booksincart', verbose_name='Книги')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='carts.cart', verbose_name='Order')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus')),
            ],
        ),
    ]
