# Generated by Django 3.2.3 on 2021-07-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(default='Новый', max_length=35, verbose_name='Статус'),
        ),
    ]
