# Generated by Django 3.2.3 on 2021-05-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='Название книги')),
                ('book_photo', models.ImageField(upload_to='', verbose_name='book img')),
                ('book_price', models.FloatField(verbose_name='price')),
                ('created', models.DateTimeField(verbose_name='Дата внесения в БД')),
            ],
        ),
    ]
