# Generated by Django 3.2.3 on 2021-05-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeroport_codes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
