# Generated by Django 3.2.3 on 2021-08-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_to', models.EmailField(max_length=254, verbose_name='Получатель')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
