# Generated by Django 3.2.3 on 2021-07-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='text', verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
